version: '3'
services:
  react-app-dev:
    build:
      context: .
      dockerfile: Dockerfile.dev
    ports:
      # <outside-world-can-access-to-the-container-at-port>:<container-port>
      # <container-port> is defined in Dockerfile.dev.
      # As default the development environment port is 3000 if you do not initialize it value
      - '3031:3000'
    env_file:
      - ./env/.env.dev
